name: Docker Image CI
on:
  push:
    branches: [ "feature-ms-elizabethSari-mensaje" ]
  pull_request:
    branches: [ "feature-ms-elizabethSari-mensaje" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
          java-version: '8'
          distribution: 'adopt'
          
    - name: Verificar Cobertura
      uses: matthijsgroen/coverage-action@v2
      with:
        coverageFile: './path/to/coverage-report'  # Ruta al archivo de cobertura
        minCoverage: 85  # Porcentaje mínimo requerido de cobertura
