name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'adopt'
    
    - name: Build and test
      run: mvn -B package -Pcoverage
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: elizabethsariu/testdevsu
        tags: latest, ${{ github.run_number }}
