name: Docker Image CI
on:
  push:
    branches: [ "feature-ms-elizabethSari-mensaje" ]
  pull_request:
    branches: [ "feature-ms-elizabethSari-mensaje" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: '1.8'
          distribution: 'adopt'
          
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
          ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
