name: CI/CD Pipeline
on:
  push:
    branches: [ "feature-ms-elizabethSari-mensaje" ]
  pull_request:
    branches: [ "feature-ms-elizabethSari-mensaje" ]

jobs:
  build:
    runs-on: self-hosted  # Esto indica que el trabajo se ejecutará en un runner alojado por ti

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: '1.8'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify  
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
          ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
    
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: elizabethsariu/ms-java-esari
        tags: latest, ${{ github.run_number }}
    
    - name: Set up Minikube
      uses: appleboy/setup-minikube@v1  # Configura Minikube
    - name: Load Docker image into Minikube
      run: |
        # Carga la imagen de Docker en Minikube
        # Antes de ejecutar este comando, asegúrate de que Minikube esté iniciado
        eval $(minikube docker-env)
        docker tag my-container-image:latest minikube:my-container-image
        kubectl apply -f minikube/deployment.yaml  # Asegúrate de tener tu archivo de deployment en la ruta adecuada

  
