name: CI/CD Pipeline
on:
  push:
    branches: [ "feature-ms-elizabethSari-mensaje" ]
  pull_request:
    branches: [ "feature-ms-elizabethSari-mensaje" ]

jobs:
  build:
    runs-on: self-hosted  # Esto indica que el trabajo se ejecutará en un runner alojado por ti

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: '1.8'

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd backend
        mvn --batch-mode --update-snapshots verify -B verify sonar:sonar -Dsonar.projectKey=eli21noe_ms-elizabethsari-java -Dsonar.organization=eli21noe -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.tests=src/test/java/tech/app/name

    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify  
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
          ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
    
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: elizabethsariu/ms-java-esari
        tags: latest, ${{ github.run_number }}
    
    - name: Set up Minikube
      run: |
        kubectl apply -f deployment.yml  # Asegúrate de tener tu archivo de deployment en la ruta adecuada

  
